// client/invite.js — recognise a co-op invite in arbitrary clipboard text.
//
// WHY: a friend shares a room by pasting the game's own invite link into WeChat / QQ / Discord. The
// desktop shell watches the clipboard so the player can answer that with one click instead of reading
// out four characters. Clipboard contents are arbitrary text written by unrelated applications, so
// this module's whole job is to be *strict*: a false positive throws a prompt over somebody's game,
// which is far worse than missing an invite (the lobby still accepts a typed code by hand).
//
// What counts as an invite (input is case-insensitive, codes come out upper-case):
//   1. a link carrying `?room=CODE` — what `inviteLink()` in `public/js/screens/room.js` produces,
//      e.g. `http://192.168.1.2:3000/?room=ABCD`. Such a link also names the host, which is how
//      "由邀请链接自动配置服务器" works;
//   2. any text containing `?room=CODE` (a chat client truncated the link, or the player copied a
//      fragment of it);
//   3. the bare code on its own (`ABCD`) — what the host reads out loud.
//
// What a CODE may be — the evidence, because this is what decides whether an ordinary word lights up
// the prompt:
//   * `server/lobby.js:69`  CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ' (letters only, no I/O);
//   * `server/lobby.js:856` genCode() draws ROOM_CODE_LEN (4) characters from that alphabet, and
//     `room.create` (`shared/protocol.js:233`) carries no client-supplied code — so every code that
//     can exist is exactly four letters of that alphabet, and a token containing a digit, an `I` or
//     an `O` cannot be one;
//   * `shared/protocol.js:234` is the *join* validator (4..6 alphanumerics). A `?room=` value taken
//     out of a link is therefore accepted at 4..6 letters, while a bare word in free text must have
//     the exact generated shape (4 letters) so that ordinary prose and `HELLO`-style words stay out.
// The alphabet is duplicated here on purpose (importing server/lobby.js would drag the whole lobby
// into the client); `test/client-invite.test.js` asserts the two stay identical.
//
// Pure module: no Electron, no clipboard access, no I/O — see client/clipboardWatcher.js for the
// sampling loop and test/client-invite.test.js for the cases this has to survive.

import { parseServerAddress } from './serverAddress.js';

/** Room-code length (`ROOM_CODE_LEN` in shared/constants.js). */
export const CODE_LEN = 4;
/** Characters a generated code can contain; mirrors CODE_ALPHABET in server/lobby.js. */
export const CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ';
/** Longest text we will even look at. A clipboard holding a document is not an invite. */
export const MAX_TEXT = 4096;

/** Hosts that mean "this very machine" — an invite link generated by a desktop client has one. */
const LOOPBACK_HOSTS = new Set(['127.0.0.1', 'localhost', '::1']);

const ALPHABET_RE = `[${CODE_ALPHABET}]`;
/** The shape a server-generated code always has (see the header). */
const BARE_CODE_RE = new RegExp(`^${ALPHABET_RE}{${CODE_LEN}}$`);
/** The shape accepted in an explicit `?room=` value (protocol's join limit). */
const LINK_CODE_RE = new RegExp(`^${ALPHABET_RE}{${CODE_LEN},${CODE_LEN + 2}}$`);
/** `?room=CODE`, `&room=CODE` or `#room=CODE` anywhere in a string. */
const ROOM_PARAM_RE = /[?&#]room=([A-Za-z0-9]+)/;
/** Any http(s)/ws(s) link inside free text; stopped at whitespace and the usual quoting/brackets. */
const URL_RE = /(?:https?|wss?):\/\/[^\s<>"'`）)】\]]+/i;
/** Trailing punctuation a chat message puts right after a link. */
const TRAILING_PUNCT_RE = /[.,;:!?、。，；：！？]+$/u;

/**
 * @typedef {object} Invite
 * @property {string} code                  upper-case room code
 * @property {'link'|'param'|'code'} source how it was recognised (a link, a `?room=` fragment, a bare code)
 * @property {string|null} url              the link as pasted, when there was one
 * @property {string|null} server          `host:port` named by the link, when it named a host
 * @property {import('./serverAddress.js').ServerAddress|null} address  the parsed host address
 * @property {boolean} loopback            the link names this machine (127.0.0.1 / localhost / ::1)
 */

/** Whether `v` is the exact shape of a server-generated code (`ABCD`). */
export function isRoomCode(v) {
  return typeof v === 'string' && BARE_CODE_RE.test(v);
}

/** Whether `v` is acceptable as an explicit `room=` value from a link (4..6 letters). */
export function isLinkRoomCode(v) {
  return typeof v === 'string' && LINK_CODE_RE.test(v);
}

/** The query string that makes the game join a room (`public/js/screens/lobby.js` `parseRoomParam`). */
export function roomQuery(code) {
  return `?room=${encodeURIComponent(String(code || ''))}`;
}

/** The first `?room=CODE` in `text`, upper-cased and validated, or null. */
function codeFromRoomParam(text) {
  const m = ROOM_PARAM_RE.exec(text);
  if (!m) return null;
  const code = m[1].toUpperCase();
  return LINK_CODE_RE.test(code) ? code : null;
}

/** The first link in `text` with chat punctuation trimmed off, or null. */
function firstUrl(text) {
  const m = URL_RE.exec(text);
  if (!m) return null;
  const raw = m[0].replace(TRAILING_PUNCT_RE, '');
  return raw.length > 1 ? raw : null;
}

/** @returns {Invite} */
function buildInvite(code, source, url, address) {
  return {
    code,
    source,
    url,
    server: address ? address.label : null,
    address: address || null,
    loopback: address ? LOOPBACK_HOSTS.has(String(address.hostname).toLowerCase()) : false,
  };
}

/**
 * Read an invite out of arbitrary text.
 * @param {unknown} input clipboard text (or anything else — non-strings never match)
 * @returns {Invite | null} null when the text is not an invite
 */
export function parseInvite(input) {
  if (typeof input !== 'string') return null;
  const text = input.trim();
  if (!text || text.length > MAX_TEXT) return null;

  const url = firstUrl(text);
  const address = url ? parseServerAddress(url) : null;

  // 1. A link that carries the room parameter: code + the host the client may have to configure.
  if (url) {
    const code = codeFromRoomParam(url);
    if (code) return buildInvite(code, 'link', url, address);
  }

  // 2. A bare `?room=ABCD` fragment; the link around it may have been eaten by the chat client.
  const paramCode = codeFromRoomParam(text);
  if (paramCode) return buildInvite(paramCode, 'param', null, address);

  // 3. The whole text is one code — the only case where a bare word is trusted.
  const bare = text.toUpperCase();
  if (BARE_CODE_RE.test(bare)) return buildInvite(bare, 'code', null, null);

  return null;
}
